# -*- coding: utf-8 -*-
SRC = '/Users/zys/caffe-extract/doc/'
OUT = '/Users/zys/caffe/docs/01-caffe-install.md'

def load(p):
    return open(SRC + p, encoding='utf-8').read().split('\n')

B  = load('CaffeInstallUserManual.txt')
V1 = load('CaffeInstallUserManual(1).txt')
V2 = load('CaffeInstallUserManual(2).txt')

def r(lines, a, b):
    return '\n'.join(lines[a-1:b])

out = []
w = out.append

w("# 服务端安装说明（Caffe Install User Manual）")
w("")
w("> 来源文件：`CaffeInstallUserManual.txt`（2017 年前后整理的安装笔记）")
w("> 合并变体：`CaffeInstallUserManual(1).txt`、`CaffeInstallUserManual(2).txt`（三份变体取并集去重，差异处以 HTML 注释标注）")
w("")
w("## Hardware Info（服务端硬件配置）")
w("")
w("| 项目 | 配置 |")
w("| --- | --- |")
for ln in B[4:7]:
    k, v = ln.split(':', 1)
    w("| " + k.strip() + " | " + v.strip() + " |")
w("| GPU | " + B[7].strip() + " |")
w("")
w("## OS（操作系统选择）")
w("")
w("### These Fails")
w("")
w("(Additional Hardware → install driver no response → relogin cannot enter desktop environment)")
w("")
w("- `ubuntu-16.10-desktop-amd64`")
w("- `UbuntuKylin-1604-ukui-amd64`")
w("")
w("### This one succeeds")
w("")
w("- YakketyYak 16.10 Minimal Boot CD | Requires an Internet LAN Connection. Wireless Wifi driver may be unavailable")
w("")
w("## Install Titan X Driver（安装 Titan X 驱动）")
w("")
w("1. Additional Drivers")
w("2. Using NVIDIA binary driver")
w("3. Apply Changes")
w("4. reboot")
w("5. Screen resolution becomes normal")
w("")
w("## Install CUDA")
w("")
w("- 下载地址：https://developer.nvidia.com/cuda-downloads")
w("<!-- 原文此行为 Word 域代码残留： HYPERLINK \"https://developer.nvidia.com/cuda-downloads\"https://developer.nvidia.com/cuda-downloads -->")
w("- Select Target Platform :  Linux > x_64_64 > Ubuntu > 16.04 (there is not a 16.10 yet) > deb (local)")
w("- Download the 1.9GB deb file. Follow the instructions:")
w("")
w("```bash")
w("sudo dpkg -i cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb")
w("sudo apt-get update")
w("sudo apt-get install cuda")
w("```")
w("<!-- 原文这三条命令是行内代码（反引号包裹），此处改为代码块，命令本身未改动 -->")
w("<!-- 原文如此：目标平台一栏写作 x_64_64 -->")
w("")
w("### Problem: /sbin/ldconfig.real: libEGL.so.1 is not a symbolic link")
w("")
w("<!-- 本节仅见于 CaffeInstallUserManual(2).txt -->")
w("")
w("```text")
w(r(V2, 37, 40))
w("```")
w("")
w("Solution:")
w("")
w("```bash")
w(r(V2, 42, 48))
w("```")
w("")
w("## Compile CUDA samples（编译 CUDA samples）")
w("")
w("```bash")
w(r(B, 37, 38))
w("```")
w("<!-- 变体差异：CaffeInstallUserManual(1).txt 与 CaffeInstallUserManual(2).txt 此处为 sudo make -j10 all -->")
w("")
w("### Error1: gcc version not supported. The system uses gcc 6")
w("")
w("Solution:")
w("")
w("```bash")
w(r(B, 43, 43))
w("```")
w("")
w("```text")
w(r(B, 45, 48))
w("```")
w("")
w("```bash")
w(r(B, 51, 59))
w("```")
w("")
w("### Error2: /usr/bin/ld: cannot find -lnvcuvid")
w("")
w("Solution:")
w("")
w("```text")
w(r(B, 63, 72))
w("```")
w("")
w("```bash")
w(r(B, 74, 78))
w("```")
w("")
w("### Run deviceQuery to make sure CUDA works")
w("")
w("```text")
w(r(B, 82, 123))
w("```")
w("")
w("## Install cudnn（安装 cuDNN）")
w("")
w("Go to Nvidia site, download and install:")
w("")
w(r(B, 129, 130))
w("<!-- 变体差异：CaffeInstallUserManual(2).txt 的列表为三项，在第一项前多出 \"1. libcudnn5_5.1.10-1+cuda8.0_amd64.deb   Runtime library\"，其余两项顺延为 2./3. -->")
w("")
w("To ensure cuDNN is installed correctly, go to /usr/src/cudnn_samples_v5/mnistCUDNN")
w("")
w("“sudo make” and test the generated mnistCUDNN:")
w("")
w("```text")
w(r(B, 136, 155))
w("```")
w("")
w("## Caffe prerequisite（Caffe 依赖库）")
w("")
w("```bash")
w("sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler")
w("sudo apt-get install --no-install-recommends libboost-all-dev")
w(r(B, 161, 162))
w("```")
w("<!-- 原文此处把下面两条命令合并在一行（提取时丢失换行），按两条命令拆开：")
w("     " + B[159])
w("     -->")
w("<!-- 变体差异：CaffeInstallUserManual(2).txt 把后两条命令合并为一行：sudo apt-get install libatlas-base-dev libgflags-dev libgoogle-glog-dev liblmdb-dev -->")
w("")
w("## Compile Caffe（编译 Caffe）")
w("")
w("### Compile NV Caffe")
w("")
w("<!-- 本节仅见于 CaffeInstallUserManual(2).txt，位于 BLVC Caffe 之前 -->")
w("")
w(V2[183])
w("")
w("```bash")
w(r(V2, 185, 195))
w("```")
w("")
w("### Compile BLVC Caffe")
w("")
w("<!-- 基础版本的章节名即 Compile Caffe，内容与本节相同 -->")
w("")
w("```bash")
w("sudo apt-get install git")
w("git clone https://github.com/BVLC/caffe.git")
w(r(B, 170, 171))
w("```")
w("<!-- 原文此处为 Word 域代码残留：" + B[168] + " -->")
w("")
w("uncomment “USE_CUDNN := 1”")
w("")
w("Revise:")
w("")
w("```makefile")
w("INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include")
w("LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib")
w("```")
w("")
w("To:")
w("")
w("```makefile")
w(B[176])
w(B[177])
w("LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/i386-linux-gnu/hdf5/serial")
w("```")
w("")
w("or")
w("")
w("```makefile")
w(B[176])
w(B[177])
w(B[178])
w("```")
w("")
w("<!-- 原文此处把 Revise/To 两段说明与两段配置合并为同一行（提取时丢失换行）：" + B[174] + " -->")
w("")
w("```text")
w(r(B, 182, 183))
w("```")
w("")
w("save & close")
w("")
w("```bash")
w(r(B, 188, 188))
w("```")
w("-j6 to enable parallel compile (i7 6800K has 6 cores)")
w("<!-- 变体差异：CaffeInstallUserManual(1).txt 与 CaffeInstallUserManual(2).txt 此处为 sudo make -j12 all，其后注释同为 \"-j12 to enable parallel compile (i7 6800K has 6 cores)\" -->")
w("")
w("### Error1: cannot find -lhdf5_hl / -lhdf5")
w("")
w("```text")
w(r(B, 193, 199))
w("```")
w("")
w("## 测试 mnist 例子：")
w("")
w("```bash")
w(r(B, 203, 206))
w("```")
w("")
w(r(B, 208, 210))
w("")
w("## Use pycaffe for prediction（用 pycaffe 做预测）")
w("")
w("```bash")
w(r(B, 218, 219))
w("```")
w("<!-- 变体差异：CaffeInstallUserManual(1).txt 与 CaffeInstallUserManual(2).txt 此处为 sudo make -j12 与 sudo make -j12 pycaffe -->")
w("")
w("error:")
w("")
w("```text")
w(r(B, 222, 222))
w("```")
w("")
w("solution:")
w("")
w("```text")
w(r(B, 225, 226))
w("```")
w("")
w("check if numpy is installed")
w("")
w("check site-packages directory")
w("")
w("```text")
w(r(B, 231, 232))
w("```")
w("")
w("Check which folder numpy is installed in.")
w("")
w("revise Makefile.config accordingly:")
w("")
w("```makefile")
w(r(B, 239, 243))
w("```")
w("")
w("```bash")
w(r(B, 247, 248))
w("```")
w("")
w("Or persist the parameter by conf file:")
w("")
w("```bash")
w("sudo gedit /etc/ld.so.conf.d/caffe.conf")
w("```")
w("")
w("add the line: /home/zys/caffe-master/distribute/lib")
w("")
w("```bash")
w("sudo ldconfig")
w("```")
w("")
w("<!-- 原文此处把这四段合并成了同一行（提取时丢失换行）：" + B[250] + " -->")
w("")
w("write a test python script file (test_googlenet.py) as follows:")
w("")
w("```python")
w(r(B, 256, 309))
w("```")
w("<!-- 原文如此：#cpu模式 注释的下一行调用的是 caffe.set_mode_gpu() -->")
w("")
w("```bash")
w(r(B, 313, 313))
w("```")
w("")

open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print("written", OUT, "parts", len(out))
